### ISSUE TITLE
Asus x299 Deluxe II new BIOS problem

### ISSUE THREAD

**Issue by wmjlxl** [shinoki7/ASUS-X299-Hackintosh#1]
hello，

first thanks for sharing.

i have one issue, if i upgrade BIOS from 0802 to 3403.
macos cannot boot anymore. 

i checked MSR lock using ControlMsrE2.efi and MSR unlock.

do you have the same issue?

bios 3403 has resize-bar support, so i want to upgrade it for playing game in windows.
of course will turn it off once in macos.

thanks.

**Comment by wmjlxl** [comment]
bios 3403 here:

https://dlcdnets.asus.com/pub/ASUS/mb/LGA2066/PRIME_X299-DELUXE_II/PRIME-X299-DELUXE-II-ASUS-3403.ZIP

**Comment by wmjlxl** [comment]
and here is the opencore debug.

[opencore-2021-04-07-120527.txt](https://github.com/shinoki7/ASUS-X299-Hackintosh/files/6271996/opencore-2021-04-07-120527.txt)

**Comment by shinoki7** [comment]
Is resizable bar off in the BIOS?  I believe it's not supported in macOS

**Comment by wmjlxl** [comment]
yes, resizable bar off.

base on opencore debug msg, i also tried to set MmioWhitelist and findout slide=0.

but still cannot access macos nor boot the usb drive.

**Comment by shinoki7** [comment]
Could you upload your EFI? Bios 0802 to 3403 is quite a jump so you may need to adjust your SSDTs.  Have you tried using my Base EFI?
