### ISSUE TITLE
WS X299 Sage macos native nvram

### ISSUE THREAD

**Issue by hh724330184** [shinoki7/ASUS-X299-Hackintosh#2]
Does the WS X299 Sage native nvram  work under macos?

**Comment by shinoki7** [comment]
Yeah it should

**Comment by hh724330184** [comment]
OK, thanks. Will gigabyte gc titan ridge2 work on this board? Any test? Or what thunderbolt card recomand?

**Comment by shinoki7** [comment]
Yes it’s the recommended card. Refer to 
https://github.com/shinoki7/ASUS-X299-Hackintosh/tree/main/Thunderbolt

**Comment by hh724330184** [comment]
Thanks again. I will learn it.
