### ISSUE TITLE
Monterey

### ISSUE THREAD

**Issue by xjwan110** [shinoki7/ASUS-X299-Hackintosh#2]
I couldn't upgrade the system to Monterey, but when I set the IOCPUNumber to 0, the installation went smoothly，What should I do？Unable to wake up from sleep, kernel panic after boot

**Comment by shinoki7** [comment]
Can you provide more information? Computer specs/EFI/version of OpenCore, etc.  Also IOCPUNumber should be adjusted to amount of threads-1.

**Comment by xjwan110** [comment]
I am using an Asus laptop, and the OC version is 0.7.0. When the Iocpunumber is adjusted to thread count -1, it cannot enter the system, but can only be 0.

**Comment by shinoki7** [comment]
Sorry you’ll have better luck asking in the hackintosh subreddit or wait for the official release for better support. My GitHub is for asus x299 builds so can’t give much support. Good luck!
